//
// Created by David Kadish on 24/03/2018.
//

#ifndef INHERITANCE_TESTING_INHERITANCETESTING_H
#define INHERITANCE_TESTING_INHERITANCETESTING_H

#include <Arduino.h>

#endif //INHERITANCE_TESTING_INHERITANCETESTING_H
